config/routes.rb
Rails.application.routes.draw do
  get "sign_up" => 'users#new', :as => "sign_up"
  resources :users
  get 'welcome/index'

  resources :anime_blogs do
    resources :comments
  end


  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime_blog.rb
class AnimeBlog < ApplicationRecord
  validates :anime_name, presence: true
  validates :desc, presence: true
  has_many :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commented_by, presence: true
  belongs_to :anime_blog
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/anime_blogs_controller.rb
class AnimeBlogsController < ApplicationController
  def new
  end

  def edit
    @blog = AnimeBlog.find(params[:id])
  end

  def create
    @blog = AnimeBlog.new(anime_blog_params)
    if @blog.save
      redirect_to @blog
    else
      redirect_to new_anime_blog_path
    end
  end

  def index
    @blogs = AnimeBlog.all
  end

  def show
    @blog = AnimeBlog.find(params[:id])
  end

  def destroy
    @blog = AnimeBlog.find(params[:id])
    @blog.destroy

    redirect_to anime_blogs_path
  end

  def update
    @blog = AnimeBlog.find(params[:id])

    if @blog.update(anime_blog_params)
      redirect_to @blog
    else
      render 'edit'
    end
  end

  private
  def anime_blog_params
    params.require(:anime_blog).permit(:anime_name, :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = AnimeBlog.find(params[:anime_blog_id])
    @comment = @blog.comments.create(comment_params)
    redirect_to anime_blog_path(@blog)
  end

  def destroy
    @blog = AnimeBlog.find(params[:anime_blog_id])
    @blog.comments.find(params[:id]).destroy
    redirect_to @blog
  end

  private
  def comment_params
    params.require(:comment).permit(:commented_by, :comment_text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed Up!"
    else
      render "new"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/anime_blogs/edit.html.erb
<h1>Edit blog</h1>

<%= form_with(model: @blog, local: true) do |form| %>

  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this blog from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :anime_name %><br>
    <%= form.text_field :anime_name ,:value=>@blog.anime_name%>
  </p>

  <p>
    <%= form.label :desc %><br>
    <%= form.text_area :desc, :value=>@blog.desc %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', anime_blogs_path %>

app/views/anime_blogs/index.html.erb
<%= render 'welcome/heading' %>
<hr>
<hr>
<% @blogs.each do |blog| %>
  <%= link_to 'Show', anime_blog_path(blog.id) %>
  <%= link_to 'Edit', edit_anime_blog_path(blog) %>
  <%= link_to 'Delete', anime_blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' } %> <br>
  <h3>Anime Name : </h3><%= blog.anime_name %>
  <h3>Description : </h3><%=  blog.desc %><br>
  <br>
  <hr>
<% end %>


<hr>

app/views/anime_blogs/new.html.erb
<%= render 'welcome/heading' %>
<div class="new-blog-form">
  <h1>Write a blog</h1>

  <%= form_with scope: :anime_blog, url: anime_blogs_path, local: true do |form| %>
    <p>
      <%= form.label :anime_name %><br>
      <%= form.text_field :anime_name, :class => 'anime_name' %>
    </p>

    <p>
      <%= form.label 'Description' %><br>
      <%= form.text_area :desc, :rows => 10, :cols => 75, :class => 'description' %>
    </p>

    <p>
      <%= form.submit :class => 'submit' %>
    </p>
  <% end %>
</div>

app/views/anime_blogs/show.html.erb
<%= render 'welcome/heading' %>
<%= link_to 'Delete', anime_blog_path(@blog.id), method: :delete, data: {confirm: 'Are you sure?'} %>
<div class="blog">
  <p>
    <strong>Topic:</strong>
    <%= @blog.anime_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @blog.desc %>
  </p>
</div>

<h2>Comments</h2>
<% @blog.comments.each do |comment| %>
  <p>
    <strong>Comment By:</strong>
    <%= comment.commented_by %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.comment_text %>
  </p>
  <%= link_to 'delete', anime_blog_comment_path(@blog, comment), method: :delete, data: {confirm: 'Are You Sure ?'} %>
<% end %>

<h2>Add a comment:</h2>
<%= form_with(model: [@blog, @blog.comments.build], local: true) do |form| %>
  <p>
    <%= form.label :commented_by %><br>
    <%= form.text_field :commented_by %>
  </p>
  <p>
    <%= form.label :comment_text %><br>
    <%= form.text_area :comment_text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= render 'welcome/heading' %>
<h1>Sign Up</h1>
<%= form_with scope: :user, url: users_path, local: true do |form| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Invalid inputs</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li>
            <% message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email, :class => 'email' %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>

  <p>
    <%= form.label :confirm_password %><br>
    <%= form.password_field :confirm_password %>
  </p>

  <p class="button">
    <%= form.submit %>
  </p>
<% end %>

app/views/welcome/_heading.erb
<%= favicon_link_tag(source='favicon.ico') %>
<div class="intro">
  <div class='topPanel'>
    <a class="titleHomeLink" href ='/'>
      <h1>Anime Blog&nbsp;&trade; </h1>
    </a>
  </div>
  <div class="homeIntro">
    <h2>Welcome to the Anime&nbsp;blog.</h2>
    <p>You can also follow us on <a href="http://www.facebook.com/animeartsindia">Facebook</a></p>
  </div>
</div>

app/views/welcome/index.html.erb
<%= render 'heading' %>
<div class="row links">
  <div class="cols">
    <%= link_to 'Create New Blog', new_anime_blog_path, :class => 'link' %> &nbsp; &nbsp;
  </div>
  <% if true %>
    <div class="col">
      <%= link_to 'Sign Up', sign_up_path, :class => 'link' %> &nbsp; &nbsp;
    </div>
  <% end %>
  <div class="col">
    <%= link_to 'View All Blogs', anime_blogs_path, :class => 'link' %>
  </div>
</div>
<div class="image">
  <%= image_tag('home.jpg') %>
</div>